apiVersion: apps/v1
kind: Deployment
metadata:
  name: recorder
  namespace: novoceo
  labels:
    app: recorder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recorder
  template:
    metadata:
      labels:
        app: recorder
    spec:
      containers:
        - name: recorder
          image: rg.fr-par.scw.cloud/funcscwjeromet1q1hfov/recorder:dev
          imagePullPolicy: Always
          env:
            - name: TZ
              value: Europe/Paris
          envFrom:
            - configMapRef:
                name: recorder-config
            - secretRef:
                name: recorder-secret
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
      restartPolicy: Always
