apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: novoceo
spec:
  type: NodePort
  selector:
    app: mosquitto
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
      nodePort: 32500
      protocol: TCP
